### PR TITLE
Proxy

### PR DESCRIPTION
**Pull request by tombisho**
Hi,

This is new function which you will either like or think that it is pointless. Try it and see which of those it is.

Tom

> prerequisites:
> - install.packages("devtools")
> - install.packages("styler")
> - install.packages("pkgdown")

#### In general:

* [x] Did you test the code against `https://armadillo.test.molgenis.org`?
no but I tested against another Opal instance
* [x] Have you ran `styler:::style_active_pkg()` to style the code-files
Yes
* [x] Have you ran `devtools::check()` to be sure documentation is rerendered and code is quality checked?
Yes

#### Vignettes:

Not done as not a vignette

1. Did you create an .orig file and add it to the pre-render.R file?
2. Did you run the the pre-render.R file to regenerate the vignettes
3. Did you run `pkgdown::build_site()` to preview the documentation

### CODE REVIEW

**Comment by timcadman** [comment]
Ha this is incredible! This is right up my street 👍 

One suggestion: when I merged the other function you wrote I tweaked it slightly to use dh.doVarsExist and dh.doesDfExist rather than ds.ClassDiscrepancy at the beginning to check whether the variable was present in all dataframes. This was because I think it's quicker than using ds.classDiscrepancy because it doesn't also look up the class. Do you want to have a look at the final code for dh.anyData and see if you agree? If so perhaps think about changing here too? If you think this way is more efficient though feel free to leave as it is.

The only other potential issue I can think of is if someone uses the "conns" argument and specifies a subset with a different set of columns than all the opal servers. If they then used this functionality, pressing tab after df$ could indicate that variables exist which don't actually in some datasets. Not a critical problem, but just a thought.

Sido - would you mind having a look as well? You said there wasn't something more complicated to do with merging a pull request from Tom's repo?

**Comment by tombisho** [comment]
Glad it might be useful!

The reason for using dh.classDiscrepancy was to use the output from it to confirm that all variables are present and of the same type in all servers. As you say, if this is not enforced your proxy object could lead you to trying to use variables that don't actually exist (your proxy is not a correct proxy!). I can see that maybe this could be made a little lighter to just check presence of variables in every server?

**Comment by timcadman** [comment]
Ah ok, I may have been hasty opting for the lighter version with the other function. Would you like me to change it back to what you had envisaged?

cheers

**Comment by sidohaakma** [comment]
This can be merged in as is. I will work on a release flow so people are not dependent on breaking code in the master branch.

**Review by sidohaakma — APPROVED** [review]

**Pull request merged**
