### PR TITLE
feat: do not use opals global object

### PR DESCRIPTION
**Pull request by sidohaakma**
- [ ] Check if the functionality still works based upon scripts of @timcadman 
- [x] Fix possible issues with not working functionality

### CODE REVIEW

**Comment by timcadman** [comment]
When I run dh.renameVars I get the error: "Error: `.l` must be a list, not a character vector"

**Comment by timcadman** [comment]
Could you also add the "conns" argument to "dh.glmTab". This was previously called regTab or something like that so you may have done that for that function

**Comment by timcadman** [comment]
For the moment could we leave dh.countRM in a separate branch? This is not yet working correctly due to problems with ds.tapply.assign - Demetris said that they will fix in the next update I think

**Comment by timcadman** [comment]
Ok they all work as used in the scripts I've written. Not to say that they won't break in other ways, but I think if you fix the things I mentioned we'll be good to merge.

**Comment by sidohaakma** [comment]
> Could you also add the "conns" argument to "dh.glmTab". This was previously called regTab or something like that so you may have done that for that function

I think the glmtab does not call any datashield methods, if you want to subset based upon the datashield backends (opals) I need to know where I need to this in the method?

**Comment by timcadman** [comment]
Ah yes, you're correct of course. That's fine - just leave it as it is

**Comment by sidohaakma** [comment]
> For the moment could we leave dh.countRM in a separate branch? This is not yet working correctly due to problems with ds.tapply.assign - Demetris said that they will fix in the next update I think

Done!

**Comment by sidohaakma** [comment]
> When I run dh.renameVars I get the error: "Error: `.l` must be a list, not a character vector"

We need to run this together this afternoon to see whats wrong.

**Pull request merged**
