### PR TITLE
added new function

### PR DESCRIPTION
**Pull request by tombisho**
Hi Tim and Sido, first attempt at a new function. Not revolutionary but I think it could help people doing SLMA with inconsistent confounders. More to come that I hope will be more useful.

Of course let me know anything I should change if this is not structured correctly

Tom

### CODE REVIEW

**Comment by timcadman** [comment]
Hi Tom - great that you're contributing to this! I'll have a look through properly and test the code tomorrow.
One thought was whether we could combine this with dh.classDescrepancy and allow people to request either a summary of missing vs non-missing data or a summary of the class of each of the variable - I'll have a think.

**Comment by timcadman** [comment]
Hi Tom, a few comments:

- I think you need to add the "datasources" argument to some of the calls to ds functions
- It would be helpful to add a "vars" argument so that you can specify a subset of a table to check 
- Might be too much work, but could you make the error message more informative if there is a variable missing from one of the tables, ie tell you which one it is and from what cohort? You could use dh.doVarsExist to do this I think.
- To be consistent with other functions, could the output be in a tibble rather than a dataframe?
- Could we change the name?! I got a bit confused with the negative. Maybe something like dh.anyData (with FALSE being completely missing) or dh.completelyMissing (with TRUE being completely missing)?

**Comment by tombisho** [comment]
Hi Tim,

Thanks for looking and for your comments! I will attempt to address them as soon as I can and resubmit.

**Comment by tombisho** [comment]
Hi Tim,

I have fixed all the things you note, and suggested a change for classDiscrepancy. I might close this PR as I have just pushed my change to the complecases branch. So please take a look at that and see if that looks better!

Thanks

Tom

**Comment by timcadman** [comment]
Closed on Tom's request as now in completecases branch

**Pull request closed without merging**
